### ISSUE TITLE
Test: ProfileEditor component needs a smoke test.

### ISSUE THREAD

**Issue by abrie** [webdevatlanta/GroupCollaborationTool#104]
Almost all the other components have a "Renders Without Crashing" test, but there is none for this one. There needs to be one.

**Comment by DanielJWagener** [comment]
I was going to tackle this, but it seems like it's been resolved?

**Comment by abrie** [comment]
Nope, I don't see a test in https://github.com/webdevatlanta/GroupCollaborationTool/tree/master/src/components/ProfileEditor folder. That'll be great!

**Comment by DanielJWagener** [comment]
Ah, silly me, I was looking at the ProjectEditor. Aight, I'll take a crack at this

**Comment by abrie** [comment]
Looks good, Thanks!
