### ISSUE TITLE
Create form to enter project details

### ISSUE THREAD

**Issue by gitchrisadams** [webdevatlanta/GroupCollaborationTool#12]

**Comment by adriantoddross** [comment]
Got feedback from the group, here are some details on what can/will be implemented!

# Form fields to include

**Name:** String, text input
**Project Name:** String, text input
**Description:** String, textarea input
**Type (open source or private):**  String, select input
**Technologies & frameworks used:** String, select (multiple) _or_ textarea input
**ID:** assigned by database or added with mock data

## Stretch goal

**Team members:** String(s), textarea (can break into a new line for each team member, will go into DB as one long string) or just take input as text input

**Comment by abrie** [comment]
Done and deployed. But we may need to revisit this with more fields later...TODO.
