### ISSUE TITLE
Login links and headers say "Login" in some places, "Sign In" in others

### ISSUE THREAD

**Issue by DanielJWagener** [webdevatlanta/GroupCollaborationTool#57]
Expected behavior: Consistent labeling of either "Login" or "Sign In" across site.

Current behavior: "Sign In" in sidebar, "Login" in header

**Comment by abrie** [comment]
Current state:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/1462268/72949959-e0221300-3d57-11ea-9da7-7e2baa1e03b5.png">
