### ISSUE TITLE
UID undefined error for New Project and Edit Project pages

### ISSUE THREAD

**Issue by chadchristensen** [webdevatlanta/GroupCollaborationTool#63]
When you try to navigate to the Create a Project or the Edit Project pages, an error is displayed 'Cannot read property 'uid' of undefined'.

The structure of `session` changed recently, so instead of accessing the `uid` by `session.user.uid` we need to access it by `session.uid`.

**Comment by abrie** [comment]
Unit tests would have caught this sort of thing.
