### ISSUE TITLE
Update UI after 'Verify' is clicked

### ISSUE THREAD

**Issue by vikram-gsu** [webdevatlanta/GroupCollaborationTool#82]
Currently, when 'Verify' is clicked, the UI updates to 'Verifying' - instead it should change to 'Check your email'

**Comment by abrie** [comment]
It starts lie this:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1462268/73411455-677d0280-42d3-11ea-8842-0408cd5b564f.png">

And here is the "verifying" page:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/1462268/73411463-719f0100-42d3-11ea-9085-8f42149b71a4.png">
