### ISSUE TITLE
Feat: Private projects should not be listed on the projects/landing page.

### ISSUE THREAD

**Issue by abrie** [webdevatlanta/GroupCollaborationTool#92]
If a project is private, then it should not be visible to the public.
The project should be listed in a view accessible only to the project owner.
This new view should be a new component, or in the Account component.
Open to debate.

**Comment by nicole-gathany** [comment]
I'm interested in solving this issue.

**Comment by abrie** [comment]
Cool!
Jump on in 🚀
If you have any questions or need help, let me know.
You can either reply here or try the Slack channel.

**Comment by nicole-gathany** [comment]
I actually do have a question. I will probably ask it tomorrow at the meetup!

**Comment by nicole-gathany** [comment]
Ok. I made private projects only visible to the user who created them. I did not make a separate component as suggested because the solution I used instead seemed more elegant to me. Please let me know what you think.

**Comment by abrie** [comment]
Closed by #117
